// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmKs9KdLYhwj2gGDLk3nnUQDPEtcFxo5A',
    appId: '1:575089326122:android:e5e24fa785ddf6f83c2b53',
    messagingSenderId: '575089326122',
    projectId: 'pamodzi-ccc3c',
    storageBucket: 'pamodzi-ccc3c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuNnSlG3SccwDjQGTD_EOS9fLFJ5tXQ_o',
    appId: '1:575089326122:web:01c675bf270af6763c2b53',
    messagingSenderId: '575089326122',
    projectId: 'pamodzi-ccc3c',
    authDomain: 'pamodzi-ccc3c.firebaseapp.com',
    storageBucket: 'pamodzi-ccc3c.firebasestorage.app',
    measurementId: 'G-HCB8GN93Z6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdPFh_tTLNhxhCfjeCVGRj3LSfCoHPLYs',
    appId: '1:575089326122:ios:56d7a7a2e32766563c2b53',
    messagingSenderId: '575089326122',
    projectId: 'pamodzi-ccc3c',
    storageBucket: 'pamodzi-ccc3c.firebasestorage.app',
    iosBundleId: 'com.example.vociferFixed',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdPFh_tTLNhxhCfjeCVGRj3LSfCoHPLYs',
    appId: '1:575089326122:ios:56d7a7a2e32766563c2b53',
    messagingSenderId: '575089326122',
    projectId: 'pamodzi-ccc3c',
    storageBucket: 'pamodzi-ccc3c.firebasestorage.app',
    iosBundleId: 'com.example.vociferFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuNnSlG3SccwDjQGTD_EOS9fLFJ5tXQ_o',
    appId: '1:575089326122:web:490774716356375f3c2b53',
    messagingSenderId: '575089326122',
    projectId: 'pamodzi-ccc3c',
    authDomain: 'pamodzi-ccc3c.firebaseapp.com',
    storageBucket: 'pamodzi-ccc3c.firebasestorage.app',
    measurementId: 'G-XKN935451P',
  );

}